name: Raspberry Pi Build and Publish

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish for ARM64
        run: dotnet publish PiTouchDate -c Release -r linux-arm64 --self-contained true -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pi-touch-date-linux-arm64
          path: ./publish
          retention-days: 2